In [2]:
#import libraries
import numpy as np
from scipy.linalg import lu

# *Lower Upper Decomposition*

In [53]:
#Lower Upper (LU) works for square matrices only
def LU(A):
    n = A.shape[0]
    U = A.copy()
    L = np.eye(n)
    
    for i in range (n):
        x = U[i,i]
        for j in range (i+1,n):
            
            L[j,i]  = U[j,i] / x
            
            U[j,:] -=  L[j,i] * U[i]#,:]
            
    return L,U
      

In [54]:
#define an example matrix
t = np.array([[2., 1., 1.],
              [4., 3., 3.],
              [8., 7., 9.]])

if (t.shape[0] != t.shape[1]):
    print("LU works for square matrices only")

In [55]:
#example of applying LU
print(t,"\n")
l, u = LU(t)
print("L matrix is:\n", l , "\n\nU matrix is:\n", u, "\n")


[[2. 1. 1.]
 [4. 3. 3.]
 [8. 7. 9.]] 

L matrix is:
 [[1. 0. 0.]
 [2. 1. 0.]
 [4. 3. 1.]] 

U matrix is:
 [[2. 1. 1.]
 [0. 1. 1.]
 [0. 0. 2.]] 



In [56]:
np.dot(l, u)

array([[2., 1., 1.],
       [4., 3., 3.],
       [8., 7., 9.]])

# *Support Vectore Decomposition*

In [57]:
from sympy import symbols, solve,Eq
import numpy.linalg as LA

In [65]:
#the example of the exercise of TD
t = np.array([[3.0,4.0],
             [0.0,5.0]])

In [66]:
#for calculating the eigen values and vectors , we should count t.T @ t
T = t.T @ t
T

array([[ 9., 12.],
       [12., 41.]])

In [67]:
#eigvalues are det(A.T @ A -lamI)=0
#eigvec (A.T@A -lamI) V = 0
eigvals,eigvecs = LA.eigh(T)
eigvals = np.sqrt(np.flipud(eigvals))
eigvals

array([6.70820393, 2.23606798])

In [68]:
#each column represent an eigenvector
eigvecs

array([[-0.9486833 ,  0.31622777],
       [ 0.31622777,  0.9486833 ]])

In [69]:
V = (np.flipud(eigvecs)).T
V

array([[ 0.31622777, -0.9486833 ],
       [ 0.9486833 ,  0.31622777]])

In [70]:
n = t.shape[0]
U = np.zeros((n,n))
U = (1/eigvals) * (t @ V) 
U

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [71]:
print('the U matrix is :\n',U,'\n \nthe singulvalues are :\n',eigvals,'\n\nthe singularvectors are:\n',V,'\n')

the U matrix is :
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]] 
 
the singulvalues are :
 [6.70820393 2.23606798] 

the singularvectors are:
 [[ 0.31622777 -0.9486833 ]
 [ 0.9486833   0.31622777]] 



In [72]:
U @ (eigvals * np.eye(2)) @ V.T

array([[3.00000000e+00, 4.00000000e+00],
       [2.22044605e-16, 5.00000000e+00]])

In [73]:
np.allclose(t,U @ (eigvals * np.eye(2)) @ V.T)

True

In [74]:
from scipy.linalg import svd
from numpy import linalg as LA
U,S,Vt = svd(t)

In [75]:
print('the U matrix is :\n',U,'\n \nthe eigenvalues are :\n',S,'\n\nthe eigenvectors are:\n',Vt,'\n')

the U matrix is :
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]] 
 
the eigenvalues are :
 [6.70820393 2.23606798] 

the eigenvectors are:
 [[ 0.31622777  0.9486833 ]
 [-0.9486833   0.31622777]] 



In [76]:
U[:,:2] @ (S *np.eye(2)) @ Vt

array([[3.00000000e+00, 4.00000000e+00],
       [2.87729942e-16, 5.00000000e+00]])

In [77]:
Vt.T

array([[ 0.31622777, -0.9486833 ],
       [ 0.9486833 ,  0.31622777]])