In [155]:
import numpy as np
from scipy.linalg import lu

'''LU works with square matrix only'''


In [129]:
#the example of the exercise of TD
t = np.array([[3.0,4.0],
             [0.0,5.0]])

In [146]:
def LU(A):
    n = A.shape[0]
    U = A.copy()
    L = np.eye(n)
    
    for i in range (n):
        x = U[i,i]
        for j in range (i+1,n):
            
            L[j,i]  = U[j,i] / x
            
            U[j,:] -=  L[j,i] * U[i,:]
            
    return L,U
      

In [148]:
m = np.array([[2.0,1.0],
              [6.0,7.0]])
print(m,"\n")
l, u = LU(m)
print("L matrix is:\n", l , "\n\nU matrix is:\n", u, "\n")
print(l @ u)

[[2. 1.]
 [6. 7.]] 

L matrix is:
 [[1. 0.]
 [3. 1.]] 

U matrix is:
 [[2. 1.]
 [0. 4.]] 

[[2. 1.]
 [6. 7.]]


In [89]:
from sympy import symbols, solve,Eq
import numpy.linalg as LA

In [130]:
#for calculating the eigen values and vectors , we should count t.T @ t
T = t.T @ t
T

array([[ 9., 12.],
       [12., 41.]])

In [131]:
#eigvalues are det(A.T @ A -lamI)=0
#eigvec (A.T@A -lamI) V = 0
eigvals,eigvecs = LA.eigh(T)
eigvals = np.sqrt(np.flipud(eigvals))
eigvals

array([6.70820393, 2.23606798])

In [132]:
#each column represent an eigenvector
eigvecs

array([[-0.9486833 ,  0.31622777],
       [ 0.31622777,  0.9486833 ]])

In [133]:
V = (np.flipud(eigvecs)).T
V

array([[ 0.31622777, -0.9486833 ],
       [ 0.9486833 ,  0.31622777]])

In [134]:
n = t.shape[0]
U = np.zeros((n,n))
U = (1/eigvals) * (t @ V) 
U

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [135]:
print('the U matrix is :\n',U,'\n \nthe singulvalues are :\n',eigvals,'\n\nthe singularvectors are:\n',V,'\n')

the U matrix is :
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]] 
 
the singulvalues are :
 [6.70820393 2.23606798] 

the singularvectors are:
 [[ 0.31622777 -0.9486833 ]
 [ 0.9486833   0.31622777]] 



In [136]:
U @ (eigvals * np.eye(2)) @ V.T

array([[3.00000000e+00, 4.00000000e+00],
       [2.22044605e-16, 5.00000000e+00]])

In [137]:
np.allclose(t,U @ (eigvals * np.eye(2)) @ V.T)

True

In [138]:
from scipy.linalg import svd
from numpy import linalg as LA
U,S,Vt = svd(t)

In [139]:
print('the U matrix is :\n',U,'\n \nthe eigenvalues are :\n',S,'\n\nthe eigenvectors are:\n',Vt,'\n')

the U matrix is :
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]] 
 
the eigenvalues are :
 [6.70820393 2.23606798] 

the eigenvectors are:
 [[ 0.31622777  0.9486833 ]
 [-0.9486833   0.31622777]] 



In [140]:
U[:,:2] @ (S *np.eye(2)) @ Vt

array([[3.00000000e+00, 4.00000000e+00],
       [2.22044605e-16, 5.00000000e+00]])

In [128]:
Vt.T

array([[ 0.37697351, -0.92622404],
       [-0.92622404, -0.37697351]])